# Generated by Django 3.0 on 2019-12-09 02:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('prime_customer', models.CharField(default='N', max_length=1)),
                ('customer_since', models.DateField(auto_now=True)),
            ],
            options={
                'ordering': ('first_name',),
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_number', models.AutoField(primary_key=True, serialize=False)),
                ('order_date', models.DateField(auto_now=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_type', models.CharField(choices=[('C', 'Credit'), ('A', 'Bank Account'), ('O', 'Other')], max_length=1)),
                ('exp_date', models.DateField(default=datetime.datetime(2020, 12, 8, 2, 29, 35, 663703))),
                ('account_number', models.CharField(max_length=20)),
                ('fk', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Amazon.Customer')),
            ],
            options={
                'ordering': ('order_number',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=25)),
                ('quantity', models.IntegerField()),
                ('fk', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Amazon.Order')),
            ],
            options={
                'ordering': ('quantity',),
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=25)),
                ('city', models.CharField(max_length=25)),
                ('state', models.CharField(max_length=25)),
                ('zip', models.CharField(max_length=10)),
                ('fk', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Amazon.Customer')),
            ],
            options={
                'ordering': ('street',),
            },
        ),
    ]
